# Generated by Django 4.1.3 on 2023-02-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genomeBact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="description",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transcript",
            name="gene",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="transcript",
            name="gene_biotype",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transcript",
            name="gene_symbol",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transcript",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "assigned"),
                    ("annotated", "annotated"),
                    ("validated", "validated"),
                    ("empty", "empty"),
                ],
                default="empty",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="status_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="transcript_biotype",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="genome",
            name="chromosome",
            field=models.CharField(
                help_text="Chromosome version name",
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transcript",
            name="annotator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_annotate",
                to="genomeBact.profile",
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="validator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genomeBact.profile",
            ),
        ),
    ]
