# Generated by Django 4.1.4 on 2023-01-29 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='id',
        ),
        migrations.AlterField(
            model_name='genome',
            name='chromosome',
            field=models.CharField(default='', help_text='Chromosome version name', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
