# Generated by Django 4.1.4 on 2023-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='validator',
            field=models.CharField(default='', max_length=100),
        ),
    ]
