# Generated by Django 4.1.4 on 2023-02-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='gene',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='gene_biotype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='gene_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='transcript_biotype',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='chromosome',
            field=models.CharField(help_text='Chromosome version name', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='annotator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genomeBact.profile'),
        ),
    ]
