# Generated by Django 4.1.4 on 2023-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Annotateur', 'Annotateur'), ('Validateur', 'Validateur'), ('Lecteur', 'Lecteur')], default='Lecteur', max_length=40),
        ),
    ]
