# Generated by Django 4.1.4 on 2023-01-13 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='start',
        ),
        migrations.AlterField(
            model_name='genome',
            name='chromosome',
            field=models.CharField(help_text='*', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genome',
            name='size',
            field=models.IntegerField(help_text='*', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='genome',
            name='specie',
            field=models.CharField(help_text='*', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='transcript',
            field=models.CharField(help_text='*', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='annotation',
        ),
    ]
