# Generated by Django 4.1.4 on 2023-02-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genomeBact.profile'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='annotator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_annotate', to='genomeBact.profile'),
        ),
    ]
