# Generated by Django 4.1.4 on 2023-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0002_transcript_description_transcript_gene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='status_date',
            field=models.DateTimeField(null=True),
        ),
    ]
