# Generated by Django 4.1.4 on 2023-01-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomeBact', '0002_remove_genome_id_alter_genome_chromosome_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='annotator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genomeBact.profile'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('annotated', 'annotated'), ('validated', 'validated'), ('empty', 'empty')], default='empty', max_length=200),
        ),
    ]
