# Generated by Django 4.1.3 on 2023-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomeBact", "0002_transcript_description_transcript_gene_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="length_nt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="length_pep",
            field=models.IntegerField(null=True),
        ),
    ]
