# Generated by Django 4.1.3 on 2023-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "genomeBact",
            "0004_rename_transcript_transcript_id_transcript_seq_cds_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="seq_cds",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="seq_nt",
            field=models.TextField(default=""),
        ),
    ]
