# Generated by Django 4.1.3 on 2023-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomeBact", "0005_alter_transcript_seq_cds_alter_transcript_seq_nt"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="start",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="stop",
            field=models.IntegerField(null=True),
        ),
    ]
