# Generated by Django 4.1.3 on 2023-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomeBact", "0010_alter_transcript_gene_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genome",
            name="size",
        ),
        migrations.RemoveField(
            model_name="genome",
            name="specie",
        ),
        migrations.AddField(
            model_name="genome",
            name="sequence",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="genome",
            name="strain",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="genome",
            name="chromosome",
            field=models.CharField(
                help_text="Chromosome version name",
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
